import Head from 'next/head';
import {
  Hero,
  Cards,
  Offers,
  Homes,
  News,
  Carousels,
  Discount,
  Overlap,
} from '../components/index';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hamro Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon 2.ico" />
      </Head>
      <Hero />
      <Carousels />
      <Cards />
      <Discount />
      <Offers />
      <Homes />
      <Overlap />
      <News />
    </div>
  );
}
